language: java
sudo: required
dist: trusty
install: true
services:
- docker
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: p1erregaultier-github
    token: $SONAR_TOKEN
script:
- mvn install:install-file -Dfile=lib/sqljdbc42.jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc42 -Dversion=4.2 -Dpackaging=jar
- mvn install:install-file -Dfile=lib/serilogj.jar -DgroupId=serilogj -DartifactId=serilogj -Dversion=0.3 -Dpackaging=jar
- cd pom-parent
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar