FROM maven:alpine as builder

ADD . /tmp/app/
WORKDIR /tmp/app/pom-parent
RUN mvn clean install

FROM java:alpine

WORKDIR /opt/sii/
COPY --from=builder /tmp/app/event/target/*.jar ./app.jar
COPY --from=builder /tmp/app/docker/application-event.yml ./application.yml

CMD ["java","-jar","app.jar"]