FROM maven as builder

ADD . /tmp/app/
WORKDIR /tmp/app/pom-parent
RUN mvn clean install

FROM java

WORKDIR /opt/sii/
COPY --from=builder /tmp/app/client/target/*.jar ./app.jar
COPY --from=builder /tmp/app/docker/application-client.yml ./application.yml

EXPOSE 8080
CMD ["java","-jar","app.jar"]