version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: pepsiirup-client:latest
    ports:
      - "4949:80"
    depends_on:
     - register
  event:
    build:
      context: .
      dockerfile: Dockerfile.event
    image: pepsiirup-event:latest
    depends_on:
     - register
  personne:
    build:
      context: .
      dockerfile: Dockerfile.personne
    image: pepsiirup-personne:latest
    depends_on:
     - register
  register:
    build:
      context: .
      dockerfile: Dockerfile.register
    image: pepsiirup-register:latest
  rabbitmq:
    image: rabbitmq
  mongo:
    image: mongo
