FROM maven as builder

COPY . /tmp/app/

WORKDIR /tmp/app/event

RUN mvn clean package

FROM java

WORKDIR /opt/sii/
COPY --from=builder /tmp/app/event/target/*.jar ./app.jar

CMD ["java","-jar","app.jar"]