version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: pepsiirup-client:latest
    ports:
      - "4949:8080"
    depends_on:
     - register
  event:
    build:
      context: .
      dockerfile: Dockerfile.event
    image: pepsiirup-event:latest
    depends_on:
     - register
     - mongo
  personne:
    build:
      context: .
      dockerfile: Dockerfile.personne
    image: pepsiirup-personne:latest
    depends_on:
     - register
     - mongo
  register:
    build:
      context: .
      dockerfile: Dockerfile.register
    image: pepsiirup-register:latest
    ports:
      - "4950:1111"
  rabbitmq:
    image: rabbitmq:alpine
  mongo:
    image: mongo
