spring:
  application:
     name: event-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/SIISTEM_EVENT

server:
  port: 8282

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/