spring:
  application:
    name: register-service  # Service registers under this name
  thymeleaf:
    enabled: false

# Configure this Discovery Server
eureka:
  instance:
    prefer-ip-address: true
    hostname: register
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:1111/eureka/
     
server:
  port: 1111   # HTTP (Tomcat) port


