spring:
    application:
        name: client

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

zuul:
  prefix: /api
  routes:
    events:
      path: /events/**
      service-id: event-service
      strip-prefix: true
      methods:
        - GET
    personnes:
      path: /personnes/**
      service-id: personne-service
      strip-prefix: true
      methods:
        - GET